name: Build dlc.dat
on:
  push:
    branches:
      - master
    paths-ignore:
      - "**/README.md"
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout codebase
        uses: actions/checkout@v4
        with:
          path: code

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: code/go.mod

      - name: Set variables
        run: |
          echo "TAG_NAME=$(date +%Y%m%d%H%M)" >> $GITHUB_ENV
          echo "CURRENT_TIME=$(date -u '+%Y-%m-%d %H:%M:%S UTC')" >> $GITHUB_ENV
        shell: bash

      - name: Build dlc.dat file
        run: |
          cd code || exit 1
          go run ./ --outputdir=../ --exportlists=category-ads-all,tld-cn,cn,tld-\!cn,geolocation-\!cn,apple,icloud

      - name: Generate dlc.dat sha256 hash
        run: |
          sha256sum dlc.dat > dlc.dat.sha256sum

      - name: Generate Zip
        run: |
          zip -9 dlc.dat.zip dlc.dat
          sha256sum dlc.dat.zip > dlc.dat.zip.sha256sum

      - name: Generate XZ
        run: |
          xz -z -9 -k dlc.dat
          sha256sum dlc.dat.xz > dlc.dat.xz.sha256sum

      - name: Release and upload assets
        run: |
          cd code || exit 1
          gh release create ${{ env.TAG_NAME }} \
            -n "This release was created automatically at ${{ env.CURRENT_TIME }} (GMT+0)." \
            -t "${{ env.CURRENT_TIME }}" \
            ../dlc.dat \
            ../dlc.dat.*
        env:
          GH_TOKEN: ${{ github.token }}
